# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Blog"
 pageRef = "blog"
 weight = 10

[[main]]
 name = "Tags"
 pageRef = "tags"
 weight = 15

[[main]]
 name = "Knowledge Base"
 pageRef = "knowledge"
 weight = 20

[[main]]
 name = "Applications"
 parent = "Knowledge Base"
 pageRef = "knowledge/applications"
 weight = 10
[[main]]
 name = "Cloud Computing"
 parent = "Knowledge Base"
 pageRef = "knowledge/cloud"
 weight = 20
[[main]]
 name = "Linux"
 parent = "Knowledge Base"
 pageRef = "knowledge/linux"
 weight = 30
[[main]]
 name = "Programming"
 parent = "Knowledge Base"
 pageRef = "knowledge/programming"
 weight = 40

[[main]]
 name = "Projects"
 pageRef = "projects"
 weight = 30

[[main]]
 name = "CV"
 pageRef = "cv"
 weight = 40

[[main]]
 identifier = "rss"
 pre = "rss"
 url = "https://rootknecht.net/index.xml"
 weight = 50

[[main]]
 identifier = "github"
 pre = "github"
 url = "https://github.com/allaman/"
 weight = 60

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Legal Notice"
  pageRef = "imprint"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  pageRef = "privacy"
  weight = 20
