---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.120.4"
          extended: true

      - name: Build
        run: hugo --minify

      - name: SSH setup
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key }}
          KNOWN_HOSTS: ${{ secrets.known_hosts }}
        run: |
          mkdir -p ~/.ssh
          echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
          echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
          echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
          chmod -R 700 ~/.ssh
      - name: Rsync deployment
        run: |
          rsync -avhr --delete -e ssh public/ hugo@rootknecht.net:/var/www/rootknecht.net/
